In [1]:
import seaborn as sns
df = sns.load_dataset('tips')

In [2]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [4]:
df.describe

<bound method NDFrame.describe of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [5]:
df['sex'].value_counts()
df['smoker'].value_counts()
df['day'].value_counts()
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
lab1= LabelEncoder()
lab2= LabelEncoder()
lab3= LabelEncoder()
lab4 = LabelEncoder()

In [7]:
df['sex']=lab1.fit_transform(df['sex'])
df['smoker']=lab2.fit_transform(df['smoker'])
df['time'] =lab3.fit_transform(df['time'])
df['day'] =lab3.fit_transform(df['time'])

In [8]:
df

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    0     0     2
1         10.34  1.66    1       0    0     0     3
2         21.01  3.50    1       0    0     0     3
3         23.68  3.31    1       0    0     0     2
4         24.59  3.61    0       0    0     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    0     0     3
240       27.18  2.00    0       1    0     0     2
241       22.67  2.00    1       1    0     0     2
242       17.82  1.75    1       0    0     0     2
243       18.78  3.00    0       0    0     0     2

[244 rows x 7 columns]

In [9]:
X= df.drop('time',axis=1)
y= df['time']

In [10]:
X

     total_bill   tip  sex  smoker  day  size
0         16.99  1.01    0       0    0     2
1         10.34  1.66    1       0    0     3
2         21.01  3.50    1       0    0     3
3         23.68  3.31    1       0    0     2
4         24.59  3.61    0       0    0     4
..          ...   ...  ...     ...  ...   ...
239       29.03  5.92    1       0    0     3
240       27.18  2.00    0       1    0     2
241       22.67  2.00    1       1    0     2
242       17.82  1.75    1       0    0     2
243       18.78  3.00    0       0    0     2

[244 rows x 6 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=0)

In [12]:
X_train

     total_bill   tip  sex  smoker  day  size
61        13.81  2.00    1       1    0     2
146       18.64  1.36    0       0    1     3
52        34.81  5.20    0       0    0     4
66        16.45  2.47    0       0    0     2
26        13.37  2.00    1       0    0     2
..          ...   ...  ...     ...  ...   ...
67         3.07  1.00    0       1    0     1
192       28.44  2.56    1       1    1     2
117       10.65  1.50    0       0    1     2
47        32.40  6.00    1       0    0     4
172        7.25  5.15    1       1    0     2

[170 rows x 6 columns]

In [15]:
from sklearn.naive_bayes import GaussianNB
GNB = GaussianNB()
GNB.fit(X_train,y_train)
y_pred = GNB.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))
print(confusion_matrix(y_pred,y_test))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        56
           1       1.00      1.00      1.00        18

    accuracy                           1.00        74
   macro avg       1.00      1.00      1.00        74
weighted avg       1.00      1.00      1.00        74

[[56  0]
 [ 0 18]]